# Build a partir da raiz de ecommerce-platform/:
#   docker build -f infrastructure/terraform/docker/Dockerfile.grafana -t <ecr-repo-url>:<tag> .
FROM grafana/grafana:latest

COPY infrastructure/grafana/provisioning/dashboards /etc/grafana/provisioning/dashboards
COPY infrastructure/terraform/docker/datasources.prod.yml /etc/grafana/provisioning/datasources/datasources.yml
